### ISSUE TITLE
Update bartercard academy styles

### ISSUE THREAD

**Issue by bradmac** [Kademi/client-bartercard#1]
Hey Brad

Can I get you to make a change to the template on the page:

http://bartercardtraining.olhub.com/programs/trade/TBPT/

You changed the text in the green box so we could read it which is great but could you make the text white instead of grey.

Cheers

Marie

**Comment by bradmac** [comment]
Hey @Uafinder, can you please look after this? Just a small change.

**Comment by Uafinder** [comment]
Hey!
Dkouk is done the requested change, but seems like he is change a whole template.
There are a several problems now:
![image](https://cloud.githubusercontent.com/assets/1945230/6534973/fc4fd0da-c449-11e4-9c54-c7dec4c1606a.png)
![image](https://cloud.githubusercontent.com/assets/1945230/6534996/3cbab13a-c44a-11e4-852c-0981cdb52fac.png)

**Comment by bradmac** [comment]
Yep, thats messed up. Needs to be fixed

**Comment by Uafinder** [comment]
Dkouk fixed both. Now there is a last question:
redirection from main page to dashboard - still struggling with it

**Comment by Uafinder** [comment]
Closing
