### ISSUE TITLE
Vouchers: display redeeming hotel

### ISSUE THREAD

**Issue by bradmac** [Kademi/client-bartercard#6]
From Joe:

Because they don’t have access across the hotels reservations systems, they need to know which hotel a booking was made at (in case they can’t find it upon check-in). They’d like to have the redeeming hotel displayed on the summary page. I.e. if someone turns up & they can’t find the reservation number associated to the voucher in their system, they would call the redeeming hotel to trouble shoot. Likewise, when they print the summary page, the redeeming hotel will be on there.

This also brings up a bit of question – does a user have a ‘main’ hotel, or will the drop down default to the first alphabetical organisation that the user is attached to?

**Comment by skwidge** [comment]
This change has been made, needs to pushed up to the beta site for testing

**Comment by skwidge** [comment]
On beta now
