### ISSUE TITLE
Vouchers: Remove release booking permission from reservations

### ISSUE THREAD

**Issue by bradmac** [Kademi/client-bartercard#8]
Joe:   Wendy’s pretty strong on not having reception staff being able to Release a booking. Can we have a new role called supervisor which has the Release role capability & we can remove this feature from reservations?

**Comment by bradmac** [comment]
Handy links...
http://pullman.kademi-beta.co/dashboard
http://admin.bartercard.kademi-beta.co/vouchers/mercure/#vouchers-tab

**Comment by skwidge** [comment]
New group called 'supervisors' added for all Accor web sites. Uses who are members of this group will be able to release a booking. All others will not.

**Comment by skwidge** [comment]
Closed
